#! /usr/bin/python
import sys,os
import socket
import subprocess
import re

def getLocalAddr():
	p = subprocess.Popen('ifconfig', stdout=subprocess.PIPE)
	output = p.communicate()
	regex = re.compile('(inet\saddr\:)((?:[0-9]{1,3}\.){3}[0-9]{1,3})')
	matches = regex.findall(str(output))
	for match in matches:
		if not match[1] == '127.0.0.1':
			return match[1]
	return None

def getDstAddr(hostname):
	try:
		ip = socket.gethostbyname_ex(hostname)
		if ip == None:
			return None
		return ip[2]
	except:
		return None

def parseUrl(url):
	hostname = ''
	path = ''
	if url.startswith('http://'):
		for i in range(7, len(url)):
			if url[i] == '/':
				hostname = url[7:i]
				path = url[i:]
				break;
		if hostname == '':
			hostname = url[7:];
		if path == '':
			path = '/'
	else:
		return None
	addr = getDstAddr(hostname)
	if addr == None:
		return None
	return [addr[0], path]

def getFName(path):
	if path == '':
		return ''
	if path == '/':
		return 'index.html'
	fname = path
	fname = fname.rstrip('/')
	i = len(fname) - 1
	while i >= 0:
		if fname[i] == '/':
			fname = fname[i+1:]
			break;
		i = i - 1
	return fname

if len(sys.argv) != 2:
	print 'Usage ./rawhttpget <url>'
	sys.exit(0)
pret = parseUrl(sys.argv[1])
if pret == None:
	print 'invalid URL'
	sys.exit(0)

cmd = './httpget %s %s %s %s' % (getLocalAddr(), pret[0], pret[1], getFName(pret[1]))
os.system(cmd)
